make: coltree.cpp entity.cpp runtime_texture.cpp runtime.cpp main.cpp
	g++ -c coltree.cpp entity.cpp runtime_texture.cpp runtime.cpp main.cpp -std=c++20 -g3
	ar rcs engine.a coltree.o entity.o runtime.o runtime_texture.o main.o 
	rm *.o